import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Navbar } from "~/components/Navbar";
import { Footer } from "~/components/Footer";

export const metadata: Metadata = {
  title: "Test",
  description: "Generated by create-t3-app",
  icons: [],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
      <ClerkProvider afterSignOutUrl="/">
        <html lang="en" className={`${GeistSans.variable}`}>
            <body>
              <div className="flex min-h-screen flex-col">
                <Navbar />
                {children}
                <Footer />
              </div>
            </body>
        </html>
      </ClerkProvider>
  );
}
