import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Navbar } from "~/components/Navbar";
import { Footer } from "~/components/Footer";
import { Toaster } from "sonner";
import { Suspense } from "react";
import Script from "next/script";
import { ThemeProvider } from "~/components/theme-provider";

export const metadata: Metadata = {
  title: "Test",
  description: "Generated by create-t3-app",
  icons: [],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en" className={`${GeistSans.variable}`} suppressHydrationWarning>
        <body>
          <ThemeProvider defaultTheme="system" storageKey="theme">
            <div className="flex min-h-screen flex-col">
              <Suspense fallback={<div className="h-16 border-b" />}>
                <Navbar />
              </Suspense>
              {children}
              <Footer />
              <Toaster />
              <Script
                src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places`}
                strategy="beforeInteractive"
              />
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
